blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/ateramua/StillnessCompiler/discussions
    about: Ask the community about QuantumIDE / StillnessCompiler here.
  - name: Extension Development
    url: https://stackoverflow.com/questions/tagged/visual-studio-code
    about: For general VS Code extension API questions, Stack Overflow remains a good resource.
