/*---------------------------------------------------------------------------------------------
 *  Copyright (c) QuantumIDE contributors. Licensed under the MIT License.
 *--------------------------------------------------------------------------------------------*/

export const enum QuantumIDEAIProvider {
	Auto = 'auto',
	OpenAI = 'openai',
	Copilot = 'copilot',
	Claude = 'claude',
	Local = 'local',
}

export const enum QuantumIDEAISettingId {
	Enabled = 'quantumide.ai.enabled',
	DefaultProvider = 'quantumide.ai.defaultProvider',
	OpenAIApiKeyStorage = 'quantumide.ai.openai.apiKeyStorage',
	OpenAIModel = 'quantumide.ai.openai.model',
	OpenAIBaseUrl = 'quantumide.ai.openai.baseUrl',
	ModelRouterRoutes = 'quantumide.ai.modelRouter.routes',
	ModelFallbackRoute = 'quantumide.ai.modelRouter.fallbackRoute',
	ModelTaskRoutes = 'quantumide.ai.modelRouter.taskRoutes',
	OpenAIGPT41Enabled = 'quantumide.ai.openai.models.gpt41.enabled',
	OpenAIGPT41MiniEnabled = 'quantumide.ai.openai.models.gpt41Mini.enabled',
	OpenAIGPT4oEnabled = 'quantumide.ai.openai.models.gpt4o.enabled',
	OpenAIStreamingEnabled = 'quantumide.ai.openai.streaming.enabled',
	OpenAIStreamingCoalesceMs = 'quantumide.ai.openai.streaming.coalesceMs',
	OpenAIStreamingAdaptiveCoalescing = 'quantumide.ai.openai.streaming.adaptiveCoalescing',
	AgentShowActivitySteps = 'quantumide.ai.agent.showActivitySteps',
	ChatAgentActivityEnabled = 'quantumide.chat.agentActivity.enabled',
	AgentActivityVerbosity = 'quantumide.ai.agent.activityVerbosity',
	AgentMaxToolIterations = 'quantumide.ai.agent.maxToolIterations',
	AgentMaxActivityStepsPerTurn = 'quantumide.ai.agent.maxActivityStepsPerTurn',
	AgentActivityDebugOutput = 'quantumide.ai.agent.activityDebugOutput',
	AgentAutoApplyEdits = 'quantumide.ai.agent.autoApplyEdits',
	AgentRequireConfirmationForTerminal = 'quantumide.ai.agent.requireConfirmationForTerminal',
	AgentRequireConfirmationForFileDelete = 'quantumide.ai.agent.requireConfirmationForFileDelete',
	AgentMaxContextFiles = 'quantumide.ai.agent.maxContextFiles',
	AgentAuditEnabled = 'quantumide.ai.agent.audit.enabled',
	IndexingEnabled = 'quantumide.ai.indexing.enabled',
	IndexingExcludePatterns = 'quantumide.ai.indexing.excludePatterns',
	SemanticIndexingEnabled = 'quantumide.ai.semanticIndexing.enabled',
	AgentVelocityProfile = 'quantumide.ai.agent.velocityProfile',
	AgentVelocityAttachWorkspaceContext = 'quantumide.ai.agent.velocity.attachWorkspaceContext',
	AgentVelocityAttachRules = 'quantumide.ai.agent.velocity.attachRules',
	AgentVelocityParallelHostTools = 'quantumide.ai.agent.velocity.parallelHostTools',
	AgentVelocityCrossRootSearch = 'quantumide.ai.agent.velocity.crossRootSearch',
	AgentVelocityHandoffEnabled = 'quantumide.ai.agent.velocity.handoffEnabled',
	// Chat panel platform (ChatPanelRe-engineering §3)
	ChatSyncRealtime = 'quantumide.chat.syncRealtime',
	WorkspaceAutoRestoreSession = 'quantumide.workspace.autoRestoreSession',
	ChatDefaultMode = 'quantumide.chat.defaultMode',
	ChatInlineEnabled = 'quantumide.chat.inline.enabled',
	ChatDiffSideBySide = 'quantumide.chat.diff.sideBySide',
	ChatTokenBudget = 'quantumide.chat.tokenBudget',
	AgentMaxEditScope = 'quantumide.agent.maxEditScope',
	AgentRetryOnError = 'quantumide.agent.retryOnError',
	AgentDangerousCommandBlock = 'quantumide.agent.dangerousCommandBlock',
	IndexingReindexOnDemand = 'quantumide.indexing.reindexOnDemand',
	IndexingEmbeddingProvider = 'quantumide.indexing.embeddingProvider',
	PrivacyLocalIndexingOnly = 'quantumide.privacy.localIndexingOnly',
	PrivacyTelemetryOptIn = 'quantumide.privacy.telemetryOptIn',
	PrivacyEncryptIndexCache = 'quantumide.privacy.encryptIndexCache',
	PerformanceEnforceBudgets = 'quantumide.performance.enforceBudgets',
	TerminalAutoApproveSafe = 'quantumide.terminal.autoApproveSafe',
	AgentAutoApplyThreshold = 'quantumide.agent.autoApplyThreshold',
	IndexingMaxCacheMb = 'quantumide.indexing.maxCacheMb',
	IndexingMaxFiles = 'quantumide.indexing.maxFiles',
	IndexingMaxFileChars = 'quantumide.indexing.maxFileChars',
	AgentIterateUntilComplete = 'quantumide.agent.iterateUntilComplete',
	AgentIterateUntilCompleteMaxContinuations = 'quantumide.agent.iterateUntilCompleteMaxContinuations',
	IndexingScaleProfile = 'quantumide.indexing.scaleProfile',
	IndexingVectorStore = 'quantumide.indexing.vectorStore',
	AgentRefactorAutoVerify = 'quantumide.agent.refactorAutoVerify',
	AgentPreferLspRename = 'quantumide.agent.preferLspRename',
	AgentInstantPaletteCommands = 'quantumide.ai.agent.instantPaletteCommands',
	AgentEditorContextSnapshot = 'quantumide.ai.agent.editorContextSnapshot',
	AgentTaskPhaseStatusEnabled = 'quantumide.ai.agent.taskPhaseStatus.enabled',
	AgentTaskPhaseStatusDismissMs = 'quantumide.ai.agent.taskPhaseStatus.dismissMs',
	AgentTaskPhaseStatusLocation = 'quantumide.ai.agent.taskPhaseStatus.location',
	ChatDiffPartialHunks = 'quantumide.chat.diff.partialHunks',
	ChatInlineGhostText = 'quantumide.chat.inline.ghostText',
	ChatCursorParityEnabled = 'quantumide.chat.cursorParity.enabled',
	ChatFeatureParityEnabled = 'quantumide.chat.featureParity.enabled',
	ChatCollabEnabled = 'quantumide.chat.collab.enabled',
	ChatAttachmentsEnabled = 'quantumide.chat.attachments.enabled',
	ChatCollabExperimental = 'quantumide.chat.collab.experimental',
	CollabExperimentalAcknowledged = 'quantumide.collab.experimentalAcknowledged',
	PluginsRequireConsent = 'quantumide.plugins.requireConsent',
}

export const QUANTUMIDE_SETTINGS_PANEL_STORAGE_KEY = 'quantumide.settings.panel.lastCategory';

export type QuantumIDEChatSettingsCategory =
	| 'general'
	| 'models'
	| 'chat'
	| 'agent'
	| 'editor'
	| 'terminal'
	| 'indexing'
	| 'privacy'
	| 'workspace'
	| 'security'
	| 'appearance'
	| 'keybindings'
	| 'accounts'
	| 'extensions'
	| 'experimental';

export const enum QuantumIDEAICommandId {
	OpenSettings = 'quantumide.settings.open',
	OpenSettingsPanel = 'quantumide.settings.openPanel',
	OpenAISettings = 'quantumide.ai.openSettings',
	OpenSettingsAI = 'quantumide.settings.openAI',
	OpenSettingsModels = 'quantumide.settings.openModels',
	OpenSettingsWorkspace = 'quantumide.settings.openWorkspace',
	OpenSettingsSecurity = 'quantumide.settings.openSecurity',
	OpenSettingsChat = 'quantumide.settings.openChat',
	OpenSettingsAgent = 'quantumide.settings.openAgent',
	OpenSettingsEditor = 'quantumide.settings.openEditor',
	OpenSettingsTerminal = 'quantumide.settings.openTerminal',
	OpenSettingsIndexing = 'quantumide.settings.openIndexing',
	OpenSettingsPrivacy = 'quantumide.settings.openPrivacy',
	OpenSettingsAppearance = 'quantumide.settings.openAppearance',
	OpenSettingsKeybindings = 'quantumide.settings.openKeybindings',
	OpenSettingsAccounts = 'quantumide.settings.openAccounts',
	OpenSettingsExtensions = 'quantumide.settings.openExtensions',
	OpenSettingsExperimental = 'quantumide.settings.openExperimental',
	InspectIndexCache = 'quantumide.ai.inspectIndexCache',
	ShowProviderStatus = 'quantumide.ai.showProviderStatus',
	StoreOpenAIApiKey = 'quantumide.ai.openai.storeApiKey',
	TestOpenAIConnection = 'quantumide.ai.openai.testConnection',
	RefreshOpenAIModels = 'quantumide.ai.openai.refreshModels',
	ClearOpenAIApiKey = 'quantumide.ai.openai.clearApiKey',
	NewAgentChat = 'quantumide.ai.newAgentChat',
	AskAboutWorkspace = 'quantumide.ai.askAboutWorkspace',
	ExplainSelection = 'quantumide.ai.explainSelection',
	ProposeFix = 'quantumide.ai.proposeFix',
	ApplyProposedSelectionEdit = 'quantumide.ai.applyProposedSelectionEdit',
	ApplyProposedFileEdits = 'quantumide.ai.applyProposedFileEdits',
	GenerateTests = 'quantumide.ai.generateTests',
	ReviewCurrentChanges = 'quantumide.ai.reviewCurrentChanges',
	RunProposedTerminalCommand = 'quantumide.ai.runProposedTerminalCommand',
	RefreshWorkspaceIndex = 'quantumide.ai.refreshWorkspaceIndex',
	PinAgentTaskSpec = 'quantumide.ai.agent.pinTaskSpec',
	ResumeAgentHandoff = 'quantumide.ai.agent.resumeHandoff',
	InlineExplain = 'quantumide.ai.inline.explain',
	InlineOptimize = 'quantumide.ai.inline.optimize',
	InlineRewrite = 'quantumide.ai.inline.rewrite',
	InlineGenerateTests = 'quantumide.ai.inline.generateTests',
	InlineAddDocs = 'quantumide.ai.inline.addDocs',
	InlineDiffAccept = 'quantumide.ai.inline.diffAccept',
	InlineDiffReject = 'quantumide.ai.inline.diffReject',
	InlineDiffAcceptHunk = 'quantumide.ai.inline.diffAcceptHunk',
	InlineDiffSideBySide = 'quantumide.ai.inline.diffSideBySide',
	InlineDiffUnified = 'quantumide.ai.inline.diffUnified',
	InlineDiffCommentHunk = 'quantumide.ai.inline.diffCommentHunk',
	InlineRefactor = 'quantumide.ai.inline.refactor',
	InlineConvertSyntax = 'quantumide.ai.inline.convertSyntax',
	InlineMigrateFramework = 'quantumide.ai.inline.migrateFramework',
	ReindexWorkspace = 'quantumide.ai.reindexWorkspace',
	ClearIndexCache = 'quantumide.ai.clearIndexCache',
	OpenSettingsPanelCategory = 'quantumide.settings.openPanelCategory',
	ShowPlatformArchitecture = 'quantumide.platform.showArchitecture',
	DetectKeybindingConflicts = 'quantumide.settings.detectKeybindingConflicts',
	ShowPerformanceReport = 'quantumide.performance.showReport',
	ChatAttachFiles = 'quantumide.chat.attachFiles',
	CollabStartSession = 'quantumide.collab.startSession',
	CollabJoinSession = 'quantumide.collab.joinSession',
	ChatShowOnboarding = 'quantumide.chat.showOnboarding',
	BrowseWorkspaceTree = 'quantumide.chat.browseWorkspaceTree',
	AcceptPendingChatEdits = 'quantumide.chat.acceptPendingEdits',
	ChatContextInspector = 'quantumide.chat.contextInspector',
	ChatReviewPendingEdits = 'quantumide.chat.reviewPendingEdits',
	ChatRunCodeBlock = 'quantumide.chat.runCodeBlock',
	ChatApplyCodeToEditor = 'quantumide.chat.applyCodeToEditor',
	ChatFixDiagnosticsInFile = 'quantumide.chat.fixDiagnosticsInFile',
	ManagePlugins = 'quantumide.plugins.manage',
	ListMatchingCommands = 'quantumide.commands.listMatching',
	ScaffoldProject = 'quantumide.scaffold.project',
	RunReplSnippet = 'quantumide.repl.runSnippet',
	ExpandQueryContext = 'quantumide.context.expandQuery',
	StartWorkflowTour = 'quantumide.onboarding.workflowTour',
	/** Fuzzy workspace file picker with live preview (QuantumIDE Chat Panel parity). */
	ParityFuzzyWorkspaceFiles = 'quantumide.parity.fuzzyWorkspaceFiles',
	ParityOpenPackageJson = 'quantumide.parity.openPackageJson',
	ParityOpenPyProject = 'quantumide.parity.openPyProject',
	ParityAddPackageScript = 'quantumide.parity.addPackageScript',
	ParityAddPackageDependency = 'quantumide.parity.addPackageDependency',
	ParityRemoveWorkspaceFolder = 'quantumide.parity.removeWorkspaceFolder',
	ParityRenameWorkspaceFolder = 'quantumide.parity.renameWorkspaceFolder',
	ParityShowNotificationCenter = 'quantumide.parity.showNotificationCenter',
	AcceptPendingBatchEdits = 'quantumide.chat.acceptPendingBatchEdits',
	RejectPendingBatchEdits = 'quantumide.chat.rejectPendingBatchEdits',
	AcceptPendingEditById = 'quantumide.chat.acceptPendingEditById',
	RejectPendingEditById = 'quantumide.chat.rejectPendingEditById',
	ChatLspGotoWorkspaceSymbol = 'quantumide.chat.lsp.gotoWorkspaceSymbol',
	ChatLspGotoDefinition = 'quantumide.chat.lsp.gotoDefinition',
	ChatLspGotoReferences = 'quantumide.chat.lsp.gotoReferences',
	ChatLspRenameSymbol = 'quantumide.chat.lsp.renameSymbol',
	ChatMoveFiles = 'quantumide.chat.moveFiles',
	ChatSplitEditorRight = 'quantumide.chat.splitEditorRight',
	ChatSplitEditorDown = 'quantumide.chat.splitEditorDown',
	ChatOpenMergeConflictUi = 'quantumide.chat.openMergeConflictUi',
	ChatLiveRefactorPreview = 'quantumide.chat.liveRefactorPreview',
	ChatCollabLiveStatus = 'quantumide.chat.collabLiveStatus',
	AgentShowTaskPhaseDetails = 'quantumide.agent.showTaskPhaseDetails',
	ChatLspRefactor = 'quantumide.chat.lsp.refactor',
	ChatLspQuickFix = 'quantumide.chat.lsp.quickFix',
	CollabConnectRelay = 'quantumide.collab.connectRelay',
	CollabDisconnectRelay = 'quantumide.collab.disconnectRelay',
	SecurityScanWorkspace = 'quantumide.security.scanWorkspace',
	ChatPanelUnifiedSearch = 'quantumide.chatPanel.unifiedSearch',
}

export const QuantumIDEOpenAIProviderId = 'openai';
export const QuantumIDEOpenAIApiKeyEnvVar = 'QUANTUMIDE_OPENAI_API_KEY';
export const QuantumIDEOpenAIBaseUrlEnvVar = 'QUANTUMIDE_OPENAI_BASE_URL';
export const QuantumIDEOpenAIStreamEnvVar = 'QUANTUMIDE_OPENAI_STREAM';
export const QuantumIDEAgentActivityEnvVar = 'QUANTUMIDE_AGENT_ACTIVITY';
export const QuantumIDEOpenAIApiKeySecretStorageKey = 'quantumide.openai.apiKey';
export const QuantumIDEOpenAIProtectedResourceId = 'https://quantumide.local/openai';
